version: 2
docker: ubuntu
plan:
  project-key: COD
  key: PLAN
  name: My Plan
  
 plan-permissions:
 - users: admin
   groups: bamboo-admins
   roles: logged-in
   permissions: view

stages:
  - Stage 1:
      jobs:
        - Job 1

Job 1:
  tasks:
    - script:
        - echo 'Hello from YAML Specs'
